--------------------------------------------------------
-- Archivo creado  - jueves-julio-04-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SECUENCIA_PROVEEDOR
--------------------------------------------------------

   CREATE SEQUENCE  "PROVEEDOR"."SECUENCIA_PROVEEDOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table PROVEEDOR
--------------------------------------------------------

  CREATE TABLE "PROVEEDOR"."PROVEEDOR" 
   (	"ID" NUMBER, 
	"RUT_PROVEEDOR" VARCHAR2(255 BYTE), 
	"NOMBRE_PROVEEDOR" VARCHAR2(255 BYTE), 
	"DIRECCION_PROVEEDOR" VARCHAR2(255 BYTE), 
	"ESPECIALIDAD_PROVEEDOR" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into PROVEEDOR.PROVEEDOR
SET DEFINE OFF;
Insert into PROVEEDOR.PROVEEDOR (ID,RUT_PROVEEDOR,NOMBRE_PROVEEDOR,DIRECCION_PROVEEDOR,ESPECIALIDAD_PROVEEDOR) values ('1','80.450.903-3','CONSTRUCTORA S.A','Av. Los leones #5445','Maquinaria Pesada');
Insert into PROVEEDOR.PROVEEDOR (ID,RUT_PROVEEDOR,NOMBRE_PROVEEDOR,DIRECCION_PROVEEDOR,ESPECIALIDAD_PROVEEDOR) values ('2','80.450.502-3','CONSTRUMARTE S.A','Av. Providencia #5445','Maquinaria General');
Insert into PROVEEDOR.PROVEEDOR (ID,RUT_PROVEEDOR,NOMBRE_PROVEEDOR,DIRECCION_PROVEEDOR,ESPECIALIDAD_PROVEEDOR) values ('3','70.550.903-4','SODIMACIN S.A','Av. Los leones #5445','Materiales Pesados');
Insert into PROVEEDOR.PROVEEDOR (ID,RUT_PROVEEDOR,NOMBRE_PROVEEDOR,DIRECCION_PROVEEDOR,ESPECIALIDAD_PROVEEDOR) values ('4','90.450.343-1','DAMOS S.A','Av. Juan Gomez #5445','Materiales Generales');
Insert into PROVEEDOR.PROVEEDOR (ID,RUT_PROVEEDOR,NOMBRE_PROVEEDOR,DIRECCION_PROVEEDOR,ESPECIALIDAD_PROVEEDOR) values ('5','82.654.403-2','MATERIAL S.A','Av. Manuel Montt #5445','Herramientas');
Insert into PROVEEDOR.PROVEEDOR (ID,RUT_PROVEEDOR,NOMBRE_PROVEEDOR,DIRECCION_PROVEEDOR,ESPECIALIDAD_PROVEEDOR) values ('6','83.464.503-4','HERRAMIENTA S.A','Av. Nueva Providencia #5445','Herramientas Generales');
Insert into PROVEEDOR.PROVEEDOR (ID,RUT_PROVEEDOR,NOMBRE_PROVEEDOR,DIRECCION_PROVEEDOR,ESPECIALIDAD_PROVEEDOR) values ('7','84.989.603-5','MAQUINARIA S.A','Av. Eduardo Leon #5445','Maquinaria, Herramientas.');
Insert into PROVEEDOR.PROVEEDOR (ID,RUT_PROVEEDOR,NOMBRE_PROVEEDOR,DIRECCION_PROVEEDOR,ESPECIALIDAD_PROVEEDOR) values ('8','85.767.703-6','DESPACHOS S.A','Av. Pedro Engel #5445','Maquinaria, Herramientas.');
Insert into PROVEEDOR.PROVEEDOR (ID,RUT_PROVEEDOR,NOMBRE_PROVEEDOR,DIRECCION_PROVEEDOR,ESPECIALIDAD_PROVEEDOR) values ('9','86.767.203-7','STREET S.A','Av. Los leones #6343','Herramientas Generales.');
Insert into PROVEEDOR.PROVEEDOR (ID,RUT_PROVEEDOR,NOMBRE_PROVEEDOR,DIRECCION_PROVEEDOR,ESPECIALIDAD_PROVEEDOR) values ('10','87.464.503-1','SILLAS S.A','Av. Los leones #1212','Maquinaria Pesada');
Insert into PROVEEDOR.PROVEEDOR (ID,RUT_PROVEEDOR,NOMBRE_PROVEEDOR,DIRECCION_PROVEEDOR,ESPECIALIDAD_PROVEEDOR) values ('11','88.757.803-2','CALLES S.A','Av. Los leones #8878','Maquinaria.');
Insert into PROVEEDOR.PROVEEDOR (ID,RUT_PROVEEDOR,NOMBRE_PROVEEDOR,DIRECCION_PROVEEDOR,ESPECIALIDAD_PROVEEDOR) values ('12','91.878.003-4','AUTOPISTAS S.A','Av. Los leones #1212','Maquinaria Pesada');
Insert into PROVEEDOR.PROVEEDOR (ID,RUT_PROVEEDOR,NOMBRE_PROVEEDOR,DIRECCION_PROVEEDOR,ESPECIALIDAD_PROVEEDOR) values ('13','91.222.123-7','RURALES S.A','Av. Los leones #4443','Maquinaria Pesada');
Insert into PROVEEDOR.PROVEEDOR (ID,RUT_PROVEEDOR,NOMBRE_PROVEEDOR,DIRECCION_PROVEEDOR,ESPECIALIDAD_PROVEEDOR) values ('14','92.323.323-8','PUBLICOS S.A','Av. Los leones #6656','Materiales');
Insert into PROVEEDOR.PROVEEDOR (ID,RUT_PROVEEDOR,NOMBRE_PROVEEDOR,DIRECCION_PROVEEDOR,ESPECIALIDAD_PROVEEDOR) values ('15','93.121.103-9','METALES S.A','Av. Los leones #6665','Maquinaria Pesada');
Insert into PROVEEDOR.PROVEEDOR (ID,RUT_PROVEEDOR,NOMBRE_PROVEEDOR,DIRECCION_PROVEEDOR,ESPECIALIDAD_PROVEEDOR) values ('16','94.220.443-2','HERRAMATERIALES S.A','Av. Los leones #2122','Maquinaria.');
Insert into PROVEEDOR.PROVEEDOR (ID,RUT_PROVEEDOR,NOMBRE_PROVEEDOR,DIRECCION_PROVEEDOR,ESPECIALIDAD_PROVEEDOR) values ('17','95.665.663-4','CONSMATERIALES S.A','Av. Los leones #2121','Maquinaria Pesada');
--------------------------------------------------------
--  DDL for Index PROVEEDOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROVEEDOR"."PROVEEDOR_PK" ON "PROVEEDOR"."PROVEEDOR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_PROVEEDOR_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PROVEEDOR"."TRIGGER_PROVEEDOR_ID" 
BEFORE INSERT ON PROVEEDOR
REFERENCING NEW AS NEW FOR EACH ROW
DECLARE valorSecuencia NUMBER := 0;
BEGIN
SELECT SECUENCIA_PROVEEDOR.NEXTVAL INTO valorSecuencia FROM DUAL;
:NEW.Id := valorSecuencia;
END;
/
ALTER TRIGGER "PROVEEDOR"."TRIGGER_PROVEEDOR_ID" ENABLE;
--------------------------------------------------------
--  Constraints for Table PROVEEDOR
--------------------------------------------------------

  ALTER TABLE "PROVEEDOR"."PROVEEDOR" ADD CONSTRAINT "PROVEEDOR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROVEEDOR"."PROVEEDOR" MODIFY ("ID" NOT NULL ENABLE);
